### ISSUE TITLE
Replcaed data.js with api

### ISSUE THREAD

**Issue by grig-ian-theo** [code4moldova/code4moldova.github.io#28]
replaced https://github.com/code4moldova/code4moldova.github.io/blob/master/data.js
with
https://services5.arcgis.com/rlT6XQbCNBKBXh0u/ArcGIS/rest/services
use that lib https://esri.github.io/arcgis-rest-js/guides/

**Comment by grig-ian-theo** [comment]
@johnsmithm dates for each were not found [req url](https://services5.arcgis.com/rlT6XQbCNBKBXh0u/ArcGIS/rest/services/cazuricovid19moldovaoperational18/FeatureServer/0/query?where=1%3D1&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&resultType=none&distance=0.0&units=esriSRUnit_Meter&returnGeodetic=false&outFields=*&returnGeometry=true&featureEncoding=esriDefault&multipatchOption=xyFootprint&maxAllowableOffset=&geometryPrecision=&outSR=&datumTransformation=&applyVCSProjection=false&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnExtentOnly=false&returnQueryGeometry=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&returnZ=false&returnM=false&returnExceededLimitFeatures=true&quantizationParameters=&sqlFormat=none&f=pgeojson)
in that [req](https://services5.arcgis.com/rlT6XQbCNBKBXh0u/ArcGIS/rest/services/tabletrend_Moldova/FeatureServer/0/query?where=1%3D1&objectIds=&time=&resultType=none&outFields=*&returnIdsOnly=false&returnUniqueIdsOnly=false&returnCountOnly=false&returnDistinctValues=false&cacheHint=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&having=&resultOffset=&resultRecordCount=&sqlFormat=none&f=pgeojson&token=). was been found only "cazuri noi" & "cazuri confirmate" and date of day

**Comment by johnsmithm** [comment]
"data" : 1584858307853,  is a time span, can be converted to date

**Comment by johnsmithm** [comment]
https://github.com/code4moldova/covid19-vizualizare-date-md/blob/master/scripts/gitapi.py
set the export GIT_PASSWORD="covid123!"
git config --global user.name  and email
then run the script
